networks:
  nexorderorders-network:
services:
  nexordersorderssql:
    container_name: nexordersorderssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - local.env
    ports:
      - 1433:1433
    volumes:
      - nexordersorderssql_data:/var/opt/mssql
    networks:
      - nexorderorders-network

  nexorder.orderservice:
    container_name: nexorderorderservice
    image: nexorderorderservice:1.1
    build:
      context: .
      dockerfile: NexOrder.OrderService/Dockerfile
    ports:
      - 7024:80
    env_file:
      - local.env
      # Following config will be needed in local.env file:-
        # DB_SERVER_NAME=nexordersorderssql
        # ACCEPT_EULA=Y
        # SA_PASSWORD=db_password
        # DB_NAME=db_name
        # DB_PASSWORD=db_password!
        # ConnectionStrings__ServiceBusConnectionString=connectionstring_for_servicebus
        # RunMigration=true
    depends_on:
      - nexordersorderssql
    networks:
      - nexorderorders-network

volumes:
  nexordersorderssql_data:
    driver: local
